version: '3.8'
services:
  oracle-fiap:
    image: gvenzl/oracle-xe
    container_name: oracle-fiap
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=fiap_password
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - app_network

  solution-api:
    build: .
    container_name: solution-api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - oracle-fiap
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  oracle-data:
