// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SolutionApi.Data;

#nullable disable

namespace SolutionApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolutionApi.Models.Abrigo", b =>
                {
                    b.Property<string>("NomeAbrigo")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Tamanho")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("NomeAbrigo");

                    b.ToTable("Abrigos");
                });

            modelBuilder.Entity("SolutionApi.Models.Aviso", b =>
                {
                    b.Property<string>("TipoAviso")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("Gravidade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Ocorrencia")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.HasKey("TipoAviso");

                    b.ToTable("Avisos");
                });

            modelBuilder.Entity("SolutionApi.Models.Pessoa", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)");

                    b.Property<string>("Carreira")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Idade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("PCD")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Nome");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("SolutionApi.Models.Voluntario", b =>
                {
                    b.Property<string>("RG")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("NomeAbrigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("RG");

                    b.HasIndex("CPF");

                    b.HasIndex("NomeAbrigo");

                    b.ToTable("Voluntarios");
                });

            modelBuilder.Entity("SolutionApi.Models.Voluntario", b =>
                {
                    b.HasOne("SolutionApi.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("CPF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolutionApi.Models.Abrigo", "Abrigo")
                        .WithMany("Voluntarios")
                        .HasForeignKey("NomeAbrigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abrigo");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("SolutionApi.Models.Abrigo", b =>
                {
                    b.Navigation("Voluntarios");
                });
#pragma warning restore 612, 618
        }
    }
}
